remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: RYTES Company Styleguide
description: The source of truth for all branding and style related to RYTES Company.
